name: employee_portal_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  file_picker: ^10.1.9
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  connectivity_plus: ^6.0.5
  dio: ^5.8.0+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  pretty_dio_logger: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/splash/
    - assets/image/onboarding/
    - assets/image/login/
    - assets/image/tab/
    - assets/image/home/
    - assets/image/person/
    - assets/image/request/
    - assets/image/day/
    - assets/translations/
    - assets/font/


  fonts:
    - family: IBMP
      fonts:
        - asset: assets/font/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/font/IBMPlexSansArabic-Light.ttf
          weight: 500

    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
